site_name: JetOBot
theme:
    name: material
    logo: assets/img/logo.png
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.path
        - navigation.indexes
        - toc.integrate
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primary: black
          accent: purple
        - scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
          primary: black
          accent: lime
    font:
        text: Roboto
        code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Bill of Materials: bill_of_materials.md
  - Hardware Setup: 
      - 3D Printing: hardware_setup/3d_printing.md
      - Assembly: hardware_setup/assembly.md
  - Software Setup:
      - Using SD Card Image: software_setup/sd_card.md
      - WiFi Setup: software_setup/wifi_setup.md
      - Using Docker Container: software_setup/docker.md
      - Native setup from scratch (No docker): software_setup/native_setup.md
  - Examples:
      - Basic Examples:
          - Simple Motion: examples/basic/simple_motion.md
          - Teleoperation: examples/basic/teleoperation.md
          - Collision Avoidance: examples/basic/collision_avoidance.md
          - Road Following: examples/basic/road_following.md
          - Object Following: examples/basic/object_following.md
      - Intermediate Examples:
          - ROS 2: examples/intermediate/ros2.md
      - Advance Examples:
          - Isaac Sim: examples/advance/isaac_sim.md
  - Reference:
      - Contributing: CONTRIBUTING.md
      - Changes: CHANGELOG.md
      - Docker Tips: reference/docker_tips.md

extra_css:
    - assets/css/extra.css   

extra:
   social:
       - icon: fontawesome/brands/github-alt
         link: https://github.com/trushant05
       - icon: fontawesome/brands/twitter
         link: https://twitter.com/_trushant_
       - icon: fontawesome/brands/linkedin
         link: https://www.linkedin.com/in/trushant-adeshara

copyright: |
    &copy; 2024 <a href="https://github.com/trushant05" target="_blank" rel="noopener">Trushant Adeshara</a>
